### ISSUE TITLE
STIX/TAXII not working for otx.alienvault.com

### ISSUE THREAD

**Issue by mr-torgue** [PaloAltoNetworks/minemeld-core#328]
I tried to create a STIX/TAXII miner for otx.alienvault.com. I used the default MineMeld taxii client for this(minemeld.ft.taxii.TaxiiClient) and the new client minemeld-taxii-ng(taxiing.Miner). 

The first client does returns the error ' module object has no attribute 'sslwrap''.
The second returns a 406 client error, which leads me to assume that something is off the accept header.

When trying another server like hailataxii.com the second client(ng) works fine. The first client does not give a SSL error but does not load IOC's.

In all cases, when I use cabby it works. 

So my questions are:
1) Why does the first Taxii client not work and why the sslwrap error?
2) Why does the second client return a 406?
3) Since cabby works pretty well: can it be turned into a node?

**Comment by phage-nz** [comment]
I just got OTX working on a new install on Ubuntu 18.04. Prototype class is minemeld.ft.taxii.TaxiiClient. At first ran into an SSLv3 neogotiation error.

The dev's should update libtaxii to 1.1.114 in the core product to address the SSL neogitation error. Workaround:

Set libtaxii==1.1.114 in:
/opt/minemeld/engine/core/minemeld_core.egg-info/requires.txt
/opt/minemeld/engine/core/requirements.txt
/opt/minemeld/local/library/constraints.txt

Update the package:
cd /opt/minemeld/engine/current/local
source bin/activate
pip install --upgrade --no-deps libtaxii

Then restart the engine and it should work.

**Comment by carlitos2007** [comment]
I am unable to do this, see below, any ideas? It is odd as i had AlienVault OTX working and it stopped a month or so ago.

(0.9.64) admin@nyserver:/opt/minemeld/engine/current/local$ pip install libtaxii==1.1.114
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting libtaxii==1.1.114
  Using cached https://files.pythonhosted.org/packages/3c/d1/95935f4ffacf65400bad5bc833ff94823cd47dc7f398ac31f9b3e4e072fd/libtaxii-1.1.114-py2.py3-none-any.whl
Requirement already satisfied: six>=1.9.0 in /opt/minemeld/engine/0.9.64/lib/python2.7/site-packages (from libtaxii==1.1.114) (1.11.0)
Requirement already satisfied: lxml>=2.2.3 in /opt/minemeld/engine/0.9.64/lib/python2.7/site-packages (from libtaxii==1.1.114) (4.1.0)
Requirement already satisfied: python-dateutil>=1.4.1 in /opt/minemeld/engine/0.9.64/lib/python2.7/site-packages (from libtaxii==1.1.114) (2.8.0)
ERROR: minemeld-core 0.9.64 has requirement libtaxii==1.1.107, but you'll have libtaxii 1.1.114 which is incompatible.
Installing collected packages: libtaxii
  Found existing installation: libtaxii 1.1.107
    Uninstalling libtaxii-1.1.107:
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/opt/minemeld/engine/0.9.64/bin/collection_information_client'
Consider using the `--user` option or check the permissions

**Comment by carlitos2007** [comment]
Could not get this working with minemeld-core but can with minemeld-ansible I do not understand what in reality the difference is but with ansible release you can use libtaxii 1.1.114 and then OTX works perfectly fine. The issue i have with minemeld-ansible is that it stops working and the web service stops working after about 12-24 hours and i need to then re run the playbook which is obviously annoying.
